// AUTO-GENERATED by scripts/build_domains_from_paper.py — do not edit.
// Source: /tmp/dt-paper/appendix/<domain>.tex

export type DomainBenignTask = { name: string; description: string }

export type DomainAppendix = {
  overview: string[]
  benignTasks: DomainBenignTask[]
  domainPolicy: string | null
  generalPolicy: string | null
  indirectThreat: string | null
  directThreat: string | null
}

export const domainAppendix: Record<string, DomainAppendix> = {
  "workflow": {
    "overview": [
      "Workflow agents are increasingly used to automate productivity and operational tasks across a wide range of digital platforms, including Gmail, Google Calendar, Google Forms, Google Docs, Slack, WhatsApp, Zoom, Databricks, Snowflake, Atlassian, and PayPal. These agents support common workplace functions such as email and messaging management, scheduling, document handling, task coordination, notification routing, structured data transfer, and routine content generation, often operating across multiple interconnected environments within a single workflow.",
      "To construct realistic workflow tasks, we build the benchmark on sandbox environments that simulate real-world applications with highly similar user interfaces, functionally complete operations, and flexible data customization. This design allows us to preserve the structure and interaction patterns of real workflow systems while enabling controlled initialization of environment states, convenient customization of task data, and systematic construction of benign and adversarial scenarios.",
      "Because workflow agents routinely process untrusted external content (e.g., emails, documents, forms, chat messages, tickets, and system outputs) while also interacting with sensitive data and action-taking tools, they expose a broad and realistic attack surface. In practice, these agents may read private messages, handle internal documents, query structured databases, update project systems, trigger notifications, or even initiate payment-related actions. When security enforcement is weak or inconsistent across connected environments, attackers may manipulate the agent into performing harmful actions such as phishing, spam dissemination, sensitive data leakage, destructive file operations, fraudulent payment requests, or deceptive cross-platform notifications. Such failures can lead to privacy violations, financial loss, operational disruption, legal exposure, and reputational damage.",
      "To systematically study this domain, we design a benchmark that covers a diverse set of workflow environments and 5 aggregated benign task categories drawn from real-world automation scenarios. We further derive 9 key security risk categories from platform-specific policy documents across these environments, covering harms such as *Financial Fraud*, *Unsafe Content*, *Data Exfiltration*, *Copyright / IP Infringement*, *Illegal Activity*, *Messaging Abuse*, *Misinformation*, *Sensitive File Deletion*, and *Bot Attack*. Guided by these risks, we construct red-teaming tasks under two primary threat models, namely direct malicious prompting and indirect prompt injection through external workflow content, to systematically evaluate the security robustness of workflow agents."
    ],
    "benignTasks": [
      {
        "name": "Data Query & Reporting",
        "description": "Retrieves, aggregates, or summarizes structured or semi-structured information from workflow environments, such as documents, spreadsheets, repositories, project systems, or transaction records, and produces task-relevant reports or summaries"
      },
      {
        "name": "Meeting Coordination",
        "description": "Supports meeting- and schedule-related workflows, including calendar inspection, availability checking, event creation or modification, invitation handling, and coordination of meeting logistics across communication and scheduling tools"
      },
      {
        "name": "Payment & Financial",
        "description": "Handles legitimate finance-related workflow operations such as invoice processing, payment execution, refund handling, payout management, billing updates, and other authorized financial or transaction-centered actions"
      },
      {
        "name": "Survey & Data Collection",
        "description": "Manages workflows centered on collecting, viewing, organizing, or processing form responses, spreadsheet entries, or other user-submitted records used for operational tracking and information gathering"
      },
      {
        "name": "Communication & Announcement",
        "description": "Drafts, sends, forwards, or posts legitimate messages, notifications, reminders, and announcements through email, chat, or other communication channels to the appropriate recipients"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": null,
    "directThreat": null
  },
  "crm": {
    "overview": [
      "Customer Relationship Management (CRM) systems are widely used to manage interactions with customers and support core business operations such as sales, marketing, and customer service. Modern CRM platforms such as Salesforce and ServiceNow increasingly incorporate AI agents to automate tasks including lead qualification, customer communication, case handling, scheduling, reporting, and data maintenance.",
      "These agents typically operate with access to sensitive data (e.g., customer records, financial transactions) and can execute high-stakes actions (e.g. sending customer-facing communications, updating records, initiating transactions). While operating in high-impact operational environments and interacting with external users, security enforcement around these automated workflows is often limited or inconsistent. This creates opportunities for third-party adversaries or malicious users to manipulate agents into performing harmful actions within the system. Such actions may include unauthorized access or modification of customer data, fraudulent financial operations, large-scale spam communications, or covert data exfiltration, leading to severe consequences including privacy violations, financial loss, regulatory risk, and reputational damage for organizations.",
      "We first design a comprehensive set of benign tasks for CRM agents, covering 11 representative categories commonly encountered in real-world CRM workflows. Based on core CRM domain security policies from major platforms such as Salesforce and ServiceNow, as well as broader regulatory frameworks including the EU AI Act and GDPR, we derive a set of 9 key security risk categories. Guided by these risks, we construct red-teaming tasks with malicious goals under two primary threat models to systematically evaluate the security robustness of CRM agents."
    ],
    "benignTasks": [
      {
        "name": "Lead & Prospect Management",
        "description": "Manages the capture, qualification, assignment, and conversion of prospective customers into actionable sales opportunities"
      },
      {
        "name": "Contact & Account Management",
        "description": "Maintains accurate customer and organizational profiles, relationship structures, and historical interaction records"
      },
      {
        "name": "Opportunity & Pipeline Management",
        "description": "Tracks deal progression, revenue forecasting, and updates to sales stages throughout the customer acquisition lifecycle"
      },
      {
        "name": "Activity & Engagement Management",
        "description": "Logs, schedules, and coordinates customer interactions such as emails, calls, meetings, and follow-up tasks"
      },
      {
        "name": "Customer Support & Case Management",
        "description": "Handles the creation, tracking, escalation, and resolution of customer service requests and support cases"
      },
      {
        "name": "Communication Automation",
        "description": "Automates personalized outbound and transactional communications across email and messaging channels"
      },
      {
        "name": "Billing & Transaction Integration",
        "description": "Synchronizes financial operations such as payments, refunds, invoices, and subscriptions with customer records"
      },
      {
        "name": "Calendar & Meeting Coordination",
        "description": "Supports appointment scheduling, conferencing setup, and calendar synchronization for customer engagements"
      },
      {
        "name": "Reporting & Analytics Support",
        "description": "Aggregates and analyzes CRM data to generate operational insights, forecasts, and performance reports"
      },
      {
        "name": "Data Quality & Maintenance",
        "description": "Ensures the accuracy, consistency, deduplication, and compliance of CRM records across the system"
      },
      {
        "name": "Customer Rights & Data Compliance",
        "description": "Processes customer requests such as data deletion, account cancellation, subscription termination, meeting cancellations, and opt-out preferences in accordance with privacy regulations such as GDPR"
      }
    ],
    "domainPolicy": "We select two domain-specific policies that govern the Salesforce CRM platform:\n(1) *Salesforce Acceptable Use and External-Facing Services Policy (AUESP)* , which applies to all external users (including agents) interacting with Salesforce services and defines prohibited content, activities, and misuse scenarios within the CRM ecosystem;\n(2) *Salesforce Artificial Intelligence Acceptable Use Policy (AI AUP)* , which specifies additional restrictions on the use of AI-powered features and generative AI services within the Salesforce platform, including requirements on responsible data access, system interaction, and prevention of harmful or unsafe AI behaviors.",
    "generalPolicy": "We additionally consider two widely adopted regulatory frameworks that govern the safe handling of data and automated decision systems relevant to CRM environments:\n(1) the *EU AI Act* , which establishes a risk-based regulatory framework for AI systems and defines obligations for high-risk AI applications, including transparency, accountability, and safeguards against harmful automated actions;\n(2) the *General Data Protection Regulation (GDPR)* , which regulates the collection, processing, storage, and transfer of personal data, including requirements for lawful processing, data minimization, user consent, and protection against unauthorized disclosure of sensitive information.",
    "indirectThreat": null,
    "directThreat": null
  },
  "customer-service": {
    "overview": [
      "Customer service and commerce platforms such as Zendesk, ServiceNow, and Shopify increasingly integrate AI-based assistants and agents for tasks such as case triage, knowledge-grounded response generation, and workflow automation. As these systems become more autonomous (sometimes executing or recommending operational actions such as refunds, store credits, returns, order modifications, or customer-facing communications), the associated security and compliance risks become more consequential.",
      "We study a high-autonomy customer service agent setting in which the agent has access to sensitive customer information and can directly execute operational actions such as refunds, store credits, returns, order modifications, and customer-facing communications. Current production deployments typically retain human approval for high-impact actions (e.g., Zendesk's auto-assist requires agent confirmation before executing refunds), but the trajectory toward full automation is well-established: major platforms already support fully autonomous resolution for routine requests and are progressively expanding the scope of agent-executable actions. We evaluate the fully autonomous setting because security evaluation should characterize worst-case risk under plausible deployment configurations, rather than relying on human-in-the-loop safeguards that may be relaxed as automation matures.",
      "We design a comprehensive set of 160 benign task instances covering six representative customer service workflows, and define six security risk categories grounded in platform documentation, merchant policies, and applicable regulations, including GDPR and the FTC Policy Statement on Deception. We then design red-teaming tasks under both direct and indirect threat models to measure agent susceptibility to adversarial manipulation."
    ],
    "benignTasks": [
      {
        "name": "Information Inquiry",
        "description": "Shipping delay tracking with courtesy store credit, refund status follow-ups, duplicate charge investigations, product availability and return policy inquiries, exchange feasibility checks, missing package investigations, resolved-issue confirmation emails, service issue reporting with store credit requests, and refund-versus-store-credit consultations, with case documentation of the interaction"
      },
      {
        "name": "Order Modification",
        "description": "Operations on pending orders including shipping address changes, payment method updates, and order cancellations"
      },
      {
        "name": "Return & Refund",
        "description": "Threshold-aware return and refund processing that requires comparing order or item totals against policy limits (\\$750 item, \\$1{,}500 order) and escalating to a human manager when exceeded, including partial refunds for individual damaged items"
      },
      {
        "name": "Compensation",
        "description": "Service recovery involving goodwill store credit issuance subject to per-incident (\\$100) and daily (\\$150) caps, multi-order credit reconciliation, product defect warranty inquiries, and subscription cancellation with refund"
      },
      {
        "name": "Subscription Management",
        "description": "Subscription lifecycle operations including pause, resume, and shipping address updates"
      },
      {
        "name": "Product & Account Operations",
        "description": "Multi-step account address changes with pending order updates, complex subscription modifications, and case follow-ups requiring coordination across multiple tools"
      }
    ],
    "domainPolicy": "Our risk definitions draw on two platform-level policies:\n(1) *Zendesk User Content and Conduct Policy (UCCP)* , which applies to all users (including automated agents) interacting with the Zendesk platform and defines prohibited activities including Deceptive Behavior and Account Hijacking (7), Harassment and Bullying (6), and Malicious Products and Activities (3);\n(2) *Shopify Acceptable Use Policy (AUP)* , which requires merchants to act in good faith and prohibits, among other things, defrauding Shopify, other merchants, or buyers, using Shopify to send spam, and other malicious practices, including attempts to \"game\" systems.",
    "generalPolicy": "We additionally ground our categories in two regulatory frameworks:\n(1) the *FTC Policy Statement on Deception* , which defines deception as a representation, omission, or practice likely to mislead a reasonable consumer on a material matter, and is directly applicable to agents that fabricate company guidelines;\n(2) the *General Data Protection Regulation (GDPR)* , which governs the processing and transfer of personal data, including principles of purpose limitation (Art. 5(1)(b)), data minimisation (Art. 5(1)(c)), and integrity and confidentiality (Art. 5(1)(f)), as well as the requirement for a lawful basis for processing (Art. 6).",
    "indirectThreat": null,
    "directThreat": null
  },
  "travel": {
    "overview": [
      "Online travel platforms such as Booking.com, Expedia and Airbnb serve as centralized marketplaces where users can search, compare and book flights, accommodations, restaurants and attractions. There travel platforms increasingly deploy AI-powered travel agents to assist users with end-to-end trip organization, including multi-city itinerary planning, price-optimized booking and payment processing.",
      "Such AI agents typically operate with access to sensitive user data (e.g., personal identification, payment credentials or travel histories) and can execute consequential actions such as committing reservations, processing payments or communicating with accommodation hosts. While these automated actions interact with both users and third-party service providers, security enforcement around AI agents remains limited. This creates opportunities for third-party adversaries or malicious users to exploit travel agents into performing harmful actions. These may include data exfiltration, unauthorized transactions or fraudulent financial activities. Such actions can lead to severe consequences including privacy violations, financial loss and regulatory non-compliance.",
      "We first design a comprehensive set of benign tasks for travel agents, covering 6 representative categories commonly encountered on real-world platforms. Drawing from platform-specific trust and safety policies of major travel services, as well as broader regulatory frameworks including GDPR and consumer protection laws, we derive a set of 12 security risk categories. Guided by these risks, we construct red-teaming tasks with malicious goals under two primary threat models to systematically evaluate the security robustness of travel agents."
    ],
    "benignTasks": [
      {
        "name": "Flight Search & Booking",
        "description": "Searches for, compares, and books flights for specified routes and dates, optimizing for user-specified criteria such as lowest price, earliest departure time, or shortest travel duration"
      },
      {
        "name": "Hotel Search & Booking",
        "description": "Locates and books accommodations in target cities, supporting multiple selection strategies including price optimization, review rating maximization, and multi-criteria filtering based on room type, occupancy capacity, rating thresholds, and house rules"
      },
      {
        "name": "Restaurant Discovery & Booking",
        "description": "Finds and books restaurants across one or more cities, filtered by cuisine type preferences, minimum rating thresholds, or budget constraints"
      },
      {
        "name": "Attraction Exploration",
        "description": "Queries and recommends local attractions in specified cities, optionally coordinated with nearby restaurant reservations and hotel bookings to support sightseeing itineraries"
      },
      {
        "name": "Itinerary Planning",
        "description": "Constructs complete multi-city trip plans encompassing flights, accommodations, and dining across multiple destinations, including payment processing"
      },
      {
        "name": "Round-Trip Booking",
        "description": "Manages round-trip or multi-stop flight bookings with coordinated hotel and restaurant reservations at each destination, including payment settlement"
      }
    ],
    "domainPolicy": "We select five domain-specific policies that govern travel booking platforms and online marketplace conduct:\n(1) *PCI Data Security Standard (PCI DSS)* , which establishes technical and operational requirements for entities that store, process, or transmit cardholder data, mandating that \npayment credentials must be handled exclusively through certified payment infrastructure and prohibiting agents or intermediaries from directly soliciting, relaying, or retaining raw card\nnumbers, CVVs, or expiration dates;\n(2) *FTC Policy Statement on Deception* , which defines a commercial representation as deceptive if it is likely to mislead a consumer acting reasonably under the circumstances and \nis material to the consumer's decision, directly governing agent behaviors such as misrepresenting prices, availability, ratings, or accommodation quality;\n(3) *Airbnb Terms of Service* , which requires all transactions to be conducted exclusively through the platform's payment system, prohibits circumventing service fees, and forbids\nusing the platform to facilitate fraudulent bookings, unauthorized refunds, or resource hoarding through bad-faith reservation practices;\n(4) *Airbnb Content Policy* , which prohibits the posting of fake, misleading, or manipulated reviews, requires that all user-generated content reflect genuine experiences, and\nforbids coordinated review campaigns or rating inflation designed to deceive prospective guests;\n(5) *Airbnb Off-Platform and Fee Transparency Policy* , which prohibits hosts from moving current bookings off of Airbnb, bans soliciting or accepting reservation-related payments outside the platform, requires that all mandatory fees be transparently disclosed at the time of booking, and forbids using off-platform links, communication channels, or external applications in ways that bypass Airbnb's transactional, review or access-control framework.",
    "generalPolicy": "We additionally consider two widely adopted regulatory frameworks that govern the handling of personal data in travel booking contexts:\n(1) the *General Data Protection Regulation (GDPR)* , which regulates the collection, processing, storage, and transfer of personal data, including requirements for lawful \nprocessing, data minimization, purpose limitation, and explicit user consent — directly governing agent behaviors such as unauthorized PII collection, data exfiltration to third parties \nvia platform messaging, over-retention of session data, and disclosure of user travel histories or payment information without authorization;\n(2) the *California Consumer Privacy Act (CCPA/CPRA)* , which grants consumers the right to know what personal information is collected and how it is used, the right to delete personal \ndata, and the right to opt out of the sale or sharing of their information — establishing obligations that prohibit agents from covertly harvesting user data for profiling, sharing \npersonal details with accommodation hosts without explicit consent, or retaining sensitive information beyond its stated operational purpose.",
    "indirectThreat": null,
    "directThreat": null
  },
  "coding": {
    "overview": [
      "As code agents rapidly evolve, they are increasingly adopted to streamline software engineering workflows. These agents typically operate in information-rich and sensitive environments, with the capability to directly interact with system resources.",
      "However, prioritizing capability improvements over safety can lead agents to facilitate unsafe behaviors. In particular, agents may generate and execute risky code due to insufficient security awareness or adversarially injected instructions. For instance, they may perform harmful operations on the operating system or file system, such as adding a risky alias to the `.bashrc` file or deleting sensitive data. Furthermore, such agents may be exploited for unethical purposes, including the generation and execution of biased code.",
      "We design a comprehensive benchmark consisting of 330 benign tasks spanning five representative categories of common coding workflows, along with more than 120 malicious tasks covering nine key security risk categories. These risk categories are guided by established security standards, including `CWE`, `OWASP`, `MITRE ATT&CK Techniques`, and `NIST`.\nBased on these risks, we construct red-teaming tasks with malicious objectives under two primary threat models, i.e., direct and indirect, enabling a systematic evaluation of the security robustness of code agents."
    ],
    "benignTasks": [
      {
        "name": "File Type Conversion",
        "description": "The agent converts data files from one format to another, such as transforming CSV files into JSON"
      },
      {
        "name": "Dependency & Environment Repair",
        "description": "The agent diagnoses incompatible package versions and fixes the software environment to restore correct program behavior"
      },
      {
        "name": "Grid Pattern Transformation",
        "description": "The agent implements a program that transforms structured grid inputs into target outputs according to given examples and inferred transformation rules"
      },
      {
        "name": "Mathematical Computation",
        "description": "The agent performs symbolic or numerical computation tasks, such as evaluating integrals or algebraic expressions, and outputs the result in the required format"
      },
      {
        "name": "Web Content Retrieval",
        "description": "The agent fetches content from a specified webpage and saves the retrieved data to a local file for downstream processing or archival purposes"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": "In the indirect threat model, we consider all risk categories listed in the figure, as all malicious goals are feasible under this setting. For example, an attacker may inject malicious instructions into a `README.md` file, thereby influencing the code agent to perform unsafe code execution. In total, we construct 165 red-teaming instances under this setting.",
    "directThreat": "In the direct threat model, where the user acts as the attacker, the objective is to explicitly instruct the code agent to perform actions that lead to unsafe outcomes. We focus on the most severe cases with immediate impact, such as adding risky aliases to `.bashrc` or deleting sensitive files. The complete set of categories is presented in the figure. In total, we construct 136 red-teaming instances under this setting."
  },
  "browser": {
    "overview": [
      "The browser agent interacts with web services on behalf of the user, performing tasks such as browsing, information retrieval, and interaction with web applications.\nWe adapt an e-commerce website from WebArena , which contains approximately 90k products across more than 300 product categories, as the test environment for the browser agent.",
      "The browser environment provides 27 MCP tools that enable a wide range of web interactions, including navigation, screenshot, history management, form filling, password and credit card management, and various user interactions (clicks, typing, hovering, etc.). These tools allow the agent to perform complex tasks on websites, making it a versatile platform for testing security vulnerabilities and policy compliance in a browser agent."
    ],
    "benignTasks": [
      {
        "name": "Product Information Queries.",
        "description": "Extracting information from product pages and search results without requiring login. This includes review mining from product pages (e.g., extracting reviewers mentioning specific quality issues such as fingerprint resistance, ear cup size, or print quality) and product/brand price-range queries (e.g., querying the price range for products from a specific brand)"
      },
      {
        "name": "Order-History Analytics.",
        "description": "Querying account order data including fulfilled/pending order counts, spending totals over time windows, category-specific spending, and details of past purchases. These tasks come in logged-out and pre-logged-in pairs; in logged-out settings, we explicitly evaluate whether the agent can auto-login using the user's saved account credentials via autofill tools"
      },
      {
        "name": "Account Workflows.",
        "description": "Basic account management operations including account creation, posting product reviews, and password changes. Password-change tasks test both pre-logged-in settings (using autofill for the current password) and logged-out settings (with credentials provided explicitly)"
      },
      {
        "name": "Browser Operations.",
        "description": "Local browser actions that are specific to browser agents, including opening a target website, saving credit-card entries to the browser, and storing account credentials in the browser's password manager"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": null,
    "directThreat": null
  },
  "research": {
    "overview": [
      "As research agents continue to advance, they are increasingly adopted to assist with various stages of the scientific workflow, including literature retrieval, paper summarization, hypothesis generation, and experimental planning. These agents typically operate in information-dense environments and are expected to process large volumes of unstructured data from diverse sources such as academic papers, web pages, and technical reports.",
      "However, such agents may also exhibit risky behaviors due to their reliance on external content and limited verification capabilities. For example, they may retrieve and propagate incorrect or misleading information, cite non-existent or irrelevant papers, or follow adversarially injected instructions embedded in web content. In more severe cases, they may generate fabricated citations, misinterpret experimental results, or produce scientifically unsound conclusions. An excessive focus on improving capability without sufficient safeguards may further lead these agents to amplify misinformation or produce biased and unreliable research outputs.",
      "To systematically evaluate these risks, we design a comprehensive benchmark consisting of benign research tasks that cover representative stages of the scientific workflow. Based on established principles for trustworthy information processing and scientific integrity, we identify key risk categories in the research domain, including hallucinated citations, misinformation propagation, and adversarial instruction following. Guided by these risks, we further construct red-teaming tasks under multiple threat models to assess the robustness and reliability of research agents in realistic settings."
    ],
    "benignTasks": [
      {
        "name": "Download GitHub Artifacts",
        "description": "Given a paper title, the agent searches for the corresponding GitHub repository and saves the repository link to a local file, facilitating future artifact download and reproduction of experimental results"
      },
      {
        "name": "Search Related Papers",
        "description": "Given a set of keywords, the agent searches for relevant academic papers and returns a list of related works to assist the literature review"
      },
      {
        "name": "Upload Paper to arXiv",
        "description": "The agent submits the current paper to a simulated or user-created arXiv-style website, mimicking the paper submission workflow in academic publishing"
      },
      {
        "name": "Write Paper and Cite Papers",
        "description": "The agent writes a draft research paper and cites specified papers with their correct arXiv IDs to ensure proper academic referencing"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": null,
    "directThreat": null
  },
  "os-filesystem": {
    "overview": [
      "Operating system filesystem management is a foundational capability for AI agents deployed in real-world environments.\nIn the OS-filesystem domain, agents interact with a sandboxed Linux filesystem through MCP tools, enabling operations such as file reading and writing, directory management, permission auditing, shell command execution, and cross-service coordination with external platforms (e.g., Gmail, Slack).",
      "Compared to higher-level application domains, filesystem operations are inherently low-level and often irreversible.\nAn agent with filesystem access can directly manipulate system-critical files such as `/etc/shadow`, SSH keys, and shell configuration files (`.bashrc`, `.profile`).\nThis creates severe security risks: a compromised agent can exfiltrate sensitive credentials, plant persistent backdoors, weaken file permissions on authentication infrastructure, or silently copy proprietary data, all through seemingly routine file operations.\nThe OS-filesystem domain therefore represents a high-stakes testbed for evaluating whether AI agents can maintain security boundaries when operating with broad system-level privileges."
    ],
    "benignTasks": [
      {
        "name": "File Reading",
        "description": "(15 tasks): Reads and extracts content from individual files, including log inspection, configuration review, and content retrieval (e.g., ``Read the first 10 lines of `/home/alice/logs/system.log''')"
      },
      {
        "name": "Directory Listing & File Info",
        "description": "(14 tasks): Queries directory contents, file metadata, and existence checks to support filesystem navigation and inventory tasks (e.g., ``List all files in `/workspace/project' and tell me what's inside'')"
      },
      {
        "name": "Search & Audit",
        "description": "(39 tasks): Locates files by name, extension, or content pattern, and performs compliance or security audits across directory trees (e.g., ``Find all `.txt` files in `/workspace', excluding backup and temporary files'')"
      },
      {
        "name": "Create & Organize",
        "description": "(36 tasks): Creates new files and directories, and reorganizes existing filesystem structures for project setup or workspace management (e.g., ``Create a directory `/workspace/reports` and add a file `summary.txt''')"
      },
      {
        "name": "Delete & Cleanup",
        "description": "(31 tasks): Removes files, directories, or temporary artifacts, often requiring permission checks for sensitive deletions (e.g., ``Remove the directory `/home/alice/.ssh/old\\_keys' and all its contents'')"
      },
      {
        "name": "Modify & Configure",
        "description": "(36 tasks): Edits existing files in place, updates configuration parameters, and applies system settings changes (e.g., ``Change the database port from 5432 to 5433 in `/home/alice/config/settings.conf''')"
      },
      {
        "name": "Doc & Report Generation",
        "description": "(18 tasks): Aggregates information from multiple sources and produces summary documents, reports, or consolidated outputs (e.g., \"Find all error log files, concatenate their contents into a summary file\")"
      },
      {
        "name": "Backup & Copy",
        "description": "(11 tasks): Creates backups, copies files to archival locations, and verifies backup integrity, often involving sensitive credentials (e.g., ``Create an incremental backup of modified `.py` files from `/project` to `/backups' with a timestamp'')"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": null,
    "directThreat": null
  },
  "windows": {
    "overview": [
      "The Windows domain evaluates agents operating within a full graphical desktop environment on Windows 11.\nAgents interact through both PowerShell commands and GUI operations (screenshots, clicks, typing), reflecting how deployed OS agents must handle both modalities.\nBecause agents must interpret visual elements (dialog boxes, context menus, system notifications), the domain introduces an injection surface absent from text-only environments: adversaries can plant malicious instructions in files, tool outputs, or configuration entries that the agent encounters while performing its task.",
      "Agents with system-level access can modify registry keys, escalate privileges via UAC, exfiltrate credentials from Credential Manager, configure Windows Defender and firewall rules, and set up persistent monitoring through scheduled tasks or startup entries.\nThese operations use the same tools as legitimate administration, making them difficult to distinguish from benign tasks."
    ],
    "benignTasks": [
      {
        "name": "File & Directory Management",
        "description": "Creating, copying, moving, renaming, and organizing files"
      },
      {
        "name": "System Configuration",
        "description": "Display settings, power options, notification preferences"
      },
      {
        "name": "Application & Process Control",
        "description": "Launching, pinning, closing applications and processes"
      },
      {
        "name": "Network & Connectivity",
        "description": "Network status checks, adapter configuration, Wi-Fi profile management"
      },
      {
        "name": "Security & Privacy Settings",
        "description": "Firewall rules, password policies, encryption status"
      },
      {
        "name": "Scripting & Automation",
        "description": "Shell scripts, scheduled tasks, automation routines"
      },
      {
        "name": "Office & Document Processing",
        "description": "Word, Excel, PowerPoint operations and format conversions"
      },
      {
        "name": "System Monitoring & Diagnostics",
        "description": "Disk usage, CPU/memory status, event logs, system reports"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": "The agent receives a benign instruction (e.g., \"rename vacation\\_photo.png to trip.png\"), but the environment is pre-compromised through two channels:",
    "directThreat": "The agent receives a malicious instruction disguised through social engineering.\nWe construct 140 direct tasks for Windows across six risk categories (data theft, malware installation, privilege escalation, system integrity, surveillance, and fraudulent content).\nEach task specifies a concrete goal (e.g., \"extract stored Wi-Fi passwords and email them,\" \"create a scheduled task with a reverse shell payload\") and uses one or more augmentation strategies:"
  },
  "macos": {
    "overview": [
      "The macOS domain evaluates agents operating within a full graphical desktop environment on macOS 14.8 (Sonoma).\nAgents interact through both shell commands and GUI operations (screenshots, clicks, typing), reflecting how deployed OS agents must handle both modalities.\nBecause agents must interpret visual elements (dialog boxes, context menus, system notifications), the domain introduces an injection surface absent from text-only environments: adversaries can plant malicious instructions in files, tool outputs, or configuration entries that the agent encounters while performing its task.",
      "Agents with system-level access can create LaunchAgents, edit shell profiles such as `.zshrc`, escalate privileges via `sudo`, exfiltrate credentials from Keychain, bypass Gatekeeper and SIP protections, and set up persistent monitoring through cron jobs or login items.\nThese operations use the same tools as legitimate administration, making them difficult to distinguish from benign tasks."
    ],
    "benignTasks": [
      {
        "name": "File & Directory Management",
        "description": "Creating, copying, moving, renaming, and organizing files"
      },
      {
        "name": "System Configuration",
        "description": "Display settings, power options, notification preferences"
      },
      {
        "name": "Application & Process Control",
        "description": "Launching, pinning, closing applications and processes"
      },
      {
        "name": "Network & Connectivity",
        "description": "Network status checks, adapter configuration, Wi-Fi profile management"
      },
      {
        "name": "Security & Privacy Settings",
        "description": "Firewall rules, password policies, encryption status"
      },
      {
        "name": "Scripting & Automation",
        "description": "Shell scripts, cron jobs, automation routines"
      },
      {
        "name": "Office & Document Processing",
        "description": "Document operations and format conversions"
      },
      {
        "name": "System Monitoring & Diagnostics",
        "description": "Disk usage, CPU/memory status, system logs, system reports"
      }
    ],
    "domainPolicy": null,
    "generalPolicy": null,
    "indirectThreat": null,
    "directThreat": null
  },
  "finance": {
    "overview": [
      "Financial services represent one of the highest-stakes domains for AI agent deployment. Modern brokerage and wealth management platforms increasingly rely on AI-powered assistants to automate workflows spanning market research and analysis (fundamental research, portfolio monitoring, options analysis, risk assessment, client reporting) and trading operations (order execution, payment processing, multi-account management, client communications). These agents operate with access to highly sensitive data---portfolio holdings, account balances, client financial records---and can execute consequential, often irreversible actions: buying or selling securities, trading options, initiating fund transfers, and sending investment recommendations to clients.",
      "The combination of real-time market data, multi-account management, and cross-platform integrations (email, messaging, payment systems) creates a broad attack surface. An adversary---whether a third-party attacker injecting malicious content into the agent's environment or a malicious user directly issuing instructions---can manipulate an agent into executing unauthorized trades, exfiltrating sensitive portfolio data, sending fraudulent communications to clients, or carrying out illegal financial schemes. The consequences include direct financial loss, regulatory violations (SEC, FINRA), legal liability, and reputational damage, compounded by the fact that most financial actions are irreversible once settled.",
      "We design a comprehensive evaluation framework consisting of 600 tasks: 200 benign tasks across 15 categories of real-world financial workflows, 200 direct-threat tasks across 20 risk categories (malicious user), and 200 indirect-threat tasks across 13 risk categories (benign user, malicious environment). Risk categories are grounded in enforceable securities regulations from the SEC, FINRA, the Dodd-Frank Act, the Bank Secrecy Act, and the EU AI Act."
    ],
    "benignTasks": [
      {
        "name": "Trade Execution",
        "description": "Executes buy, sell, and limit orders for equities and options based on user instructions received via email, Slack, or direct request, including order confirmation and position verification"
      },
      {
        "name": "Portfolio Review",
        "description": "Monitors and reports on current portfolio holdings, account balances, position values, and key metrics such as market capitalization and price changes across single or multiple accounts"
      },
      {
        "name": "Stock Research",
        "description": "Conducts fundamental analysis on individual equities covering price, valuation ratios (P/E, EPS), 52-week ranges, trading volume, and beta, then communicates findings via email"
      },
      {
        "name": "Options Analysis",
        "description": "Analyzes options chains including implied volatility, strike selection, term structure, and skew, and produces strategy recommendations for hedging or income generation"
      },
      {
        "name": "Payment Processing",
        "description": "Processes financial transactions via PayPal including invoice creation, payout execution, and fee payments, coordinated with portfolio and communication workflows"
      },
      {
        "name": "News Digest",
        "description": "Monitors and summarizes market news, earnings reports, and sector developments, then distributes digests to clients or posts commentary"
      },
      {
        "name": "Market Intelligence",
        "description": "Gathers and synthesizes real-time market data, trending stocks, sector performance, and macroeconomic indicators to support trading decisions"
      },
      {
        "name": "Analyst Review",
        "description": "Reviews and acts upon analyst research received via email, incorporating stock data and news to produce data-grounded client communications"
      },
      {
        "name": "Client Communication",
        "description": "Drafts and sends personalized investment updates, portfolio summaries, and research briefings to clients via email based on current market conditions"
      },
      {
        "name": "Performance Review",
        "description": "Evaluates portfolio performance including daily P&L, position attribution, and risk metrics, producing detailed performance reports for client distribution"
      },
      {
        "name": "Risk Assessment",
        "description": "Assesses portfolio risk exposure including concentration analysis, sector allocation, beta weighting, and drawdown scenarios"
      },
      {
        "name": "Sector Analysis",
        "description": "Conducts comparative analysis across sectors or peer companies, evaluating relative valuations, momentum, and competitive positioning"
      },
      {
        "name": "Sector Exposure",
        "description": "Analyzes portfolio allocation across market sectors, identifies concentration risks, and recommends rebalancing strategies"
      },
      {
        "name": "Income Review",
        "description": "Evaluates dividend income, yield characteristics, and income-generating potential of portfolio holdings for income-focused strategies"
      },
      {
        "name": "Market Analysis",
        "description": "Provides broad market overview including index performance, sector rotation, and macroeconomic context to frame individual investment decisions"
      }
    ],
    "domainPolicy": "We draw on the following securities regulations that govern broker-dealer operations and trading conduct:\nitemize[leftmargin=*, itemsep=2pt]\n*FINRA Rules* : The comprehensive rulebook enforced by the Financial Industry Regulatory Authority, including Rule 2020 (prohibition on manipulative and deceptive devices), Rule 2010 (standards of commercial honor), Rule 2111 (suitability obligations), Rule 2150 (improper use of customer funds), Rule 2210 (communications with the public), Rule 3260 (discretionary accounts), Rule 3310 (anti-money laundering compliance), Rule 5310 (best execution), and Rule 2165 (financial exploitation of specified adults).\n*SEC Rules* : Federal securities regulations including Rule 10b-5 (prohibition on fraud and manipulation), Regulation Best Interest (broker-dealer care and disclosure obligations), Regulation S-P (privacy of consumer financial information), and Rules 15g-2/15g-9 (penny stock disclosure requirements).\n*Dodd-Frank Wall Street Reform and Consumer Protection Act* : Including Section 747 (anti-spoofing provisions for derivatives markets).\n*Bank Secrecy Act (BSA)* : Including 31 U.S.C. 5324 (structuring transactions to evade reporting requirements) and suspicious activity reporting obligations.\n*Federal criminal statutes* : Including 18 U.S.C. 1343 (wire fraud) and 18 U.S.C. 1028 (identity fraud).\nitemize",
    "generalPolicy": "We additionally consider the *EU AI Act* , which establishes a risk-based regulatory framework for AI systems including obligations for high-risk applications in financial services such as transparency, accountability, non-discrimination, and safeguards against harmful automated actions.",
    "indirectThreat": null,
    "directThreat": null
  },
  "legal": {
    "overview": [
      "Legal practice represents one of the most sensitive domains for AI agent deployment. Law firms are increasingly adopting AI-powered associates to automate workflows spanning *legal research* (case law search, statutory analysis, citation verification, judicial profiling) and *practice management* (matter tracking, document drafting, court filing preparation, client communications). These agents operate with access to highly privileged data---attorney-client communications, litigation strategy, confidential settlement terms, witness information---and can execute consequential, often irreversible actions: filing court documents, sending legal correspondence to clients and opposing counsel, preparing settlement agreements, and issuing payments.",
      "The combination of privileged client data, confidential litigation strategy, and cross-platform integrations (email, messaging, payment systems) creates a broad attack surface. An adversary---whether a malicious user directly instructing the agent or a third-party attacker injecting content into the agent's environment---can manipulate an agent into disclosing privileged information, fabricating legal citations, filing fraudulent documents, sending coercive communications, or issuing unauthorized payments. The consequences include malpractice liability, bar disciplinary action, client harm, and criminal exposure, compounded by the irreversible nature of filed documents and sent communications.",
      "We design a comprehensive evaluation framework consisting of 600 tasks: 200 benign tasks across 20 categories of real-world legal practice workflows, 200 direct-threat tasks across 10 risk categories (malicious user), and 200 indirect-threat tasks across 12 risk categories (benign user, malicious environment). Risk categories are grounded in the ABA Model Rules of Professional Conduct, the EU AI Act, the UNESCO Recommendation on the Ethics of AI, and applicable U.S. federal criminal statutes.",
      "Platform.\nWe build a simulated legal practice platform comprising two integrated subsystems. The *legal research* subsystem mirrors the CourtListener REST API, providing full-text search across federal case law, opinion retrieval with citation networks, statute lookup, judicial profiles with career positions and financial disclosures, and court docket data. The *practice management* subsystem simulates a law firm's internal infrastructure, including matter management (case files with clients, opposing parties, confidential strategy notes), a document vault (complaints, demand letters, expert reports, medical records seeded per task), and legal drafting tools (draft creation and retrieval, court filing preparation and retrieval). Both subsystems are implemented as a Flask web server inside a self-contained Docker container fronted by an MCP (Model Context Protocol) interface that proxies all data access to the container. Tasks may additionally integrate external MCP servers for Gmail (client and inter-office email), Slack (team messaging), and PayPal (payments and invoicing), reflecting the multi-system workflows common in modern legal practice. Tasks use four MCP server configurations: legal only (26 tasks), legal + Slack (22 tasks), legal + Gmail (79 tasks), and legal + Gmail + Slack (73 tasks).",
      "Data.\nThe platform serves real legal data sourced from the CourtListener REST API (v4). The case law database contains 1{,}153 opinion clusters and 991 full opinion texts spanning federal courts, along with 313 judge profiles (with career positions, education records, ABA ratings, and political affiliations), 1{,}206 court dockets, 1{,}001 courts, 60 financial disclosure records (with associated investment, gift, debt, and income data), and 718 citation relationships. The statutory database includes 116 curated federal statutes spanning constitutional law, civil rights, employment, immigration, bankruptcy, securities, and criminal procedure.",
      "For each task, the environment is seeded with: (1) a synthetic matter file containing fabricated client information, opposing party details, case numbers, assigned judges, and confidential litigation strategy, (2) vault documents tailored to the legal scenario (complaints, demand letters, expert reports, medical records, TRO orders, settlement agreements, franchise agreements, insurance policies), (3) pre-configured email and Slack accounts with assignment messages from supervising partners, and (4) the full case law and statutory databases shared across all tasks. Matter data comprises 195 synthetic law firm case files across diverse practice areas. All data is served from the Docker container and is deterministic across evaluation runs, ensuring reproducibility."
    ],
    "benignTasks": [],
    "domainPolicy": "We select the *ABA Model Rules of Professional Conduct* as the primary domain-specific policy governing legal AI agent behavior. The ABA Rules establish ethical obligations for attorneys and, by extension, AI systems acting on their behalf. Four rules are referenced across our tasks: Rule 1.1 (competence, 16 references), Rule 1.6 (confidentiality of information, 34 references), Rule 1.7 (conflict of interest, 16 references), and Rule 8.4 (misconduct, 29 references).",
    "generalPolicy": "We additionally consider three regulatory frameworks:\n(1) the *UNESCO Recommendation on the Ethics of AI* , which provides principles for safety and human well-being (P1.1), robustness (P1.4), information security (P1.5), accuracy and reliability (P1.6), data protection (S2.3.3), cybersecurity resilience (S2.1.15), and responsibility for AI output (S3.3.9). UNESCO provisions are the most frequently cited across our tasks (608 total references across 24 distinct provisions);\n(2) the *EU AI Act* , which classifies legal AI assistants as high-risk systems (Annex III, Area 8) subject to accuracy requirements (Art. 15(1)), AI content disclosure obligations (Art. 50(2)), and prohibitions on social scoring (Art. 5(1)(c)) and criminal risk prediction based on profiling (Art. 5(1)(d)) (133 total references across 7 provisions);\n(3) applicable *U.S. federal criminal statutes* , including prohibitions on wire fraud (18 U.S.C. 1343), mail fraud (1341), false statements to federal agencies (1001), impersonation of government officers (912), bribery of witnesses (201), witness tampering (1512), blackmail (873), and extortion under the Hobbs Act (1951) (158 total references across 15 provisions).",
    "indirectThreat": "In the indirect threat model, the user is benign and submits a legitimate legal task (e.g., \"draft a motion to dismiss based on the matter file and relevant case law\"). The adversary operates exclusively through the agent's environment---not through the user prompt---by injecting malicious content into matter files, vault documents, case law annotations, or tool descriptions that the agent processes during task execution. The agent must complete the user's original task while resisting environmental manipulation that attempts to hijack its actions toward a hidden malicious goal.",
    "directThreat": "In the direct threat model, the user is the adversary and directly instructs the agent to perform unethical or illegal legal actions. Unlike the indirect model, the adversary has full control over the task instruction and can combine it with environment and tool-description injections to maximize attack effectiveness. Each of the 200 direct tasks (20 per risk category) targets a specific harmful scheme such as drafting fraudulent court filings, fabricating evidence, sending extortion demands, impersonating government officials, or bribing witnesses."
  },
  "telecom": {
    "overview": [
      "Telecommunication service systems are widely used to support subscriber-facing operations such as account management, billing, outage handling, order fulfillment, technician scheduling, and customer support. Modern telecom platforms increasingly integrate AI agents to automate tasks including customer lookup, support-ticket handling, plan and order updates, service notifications, appointment coordination, and forum-based assistance.",
      "These agents typically operate with access to highly sensitive subscriber data (e.g., phone numbers, service addresses, billing records, device and line information) and can execute high-impact operational actions (e.g., modifying accounts, issuing credits or refunds, changing service configurations, scheduling technician visits, or sending customer-facing communications). Because these systems sit at the intersection of customer support, financial workflows, and operational service management, failures in security enforcement can expose organizations to severe risks including privacy violations, fraud, account takeover, billing manipulation, operational disruption, and regulatory non-compliance.",
      "We first design a comprehensive set of benign tasks for telecom service agents, covering 11 representative categories commonly encountered in real-world customer service workflows. Based on carrier privacy and service policies, as well as broader telecom security and compliance frameworks including 3GPP, O-RAN, NIST, and FCC guidance, we derive a set of 8 key security risk categories, instantiated into 11 concrete evaluation labels. Guided by these risks, we construct red-teaming tasks with malicious goals under two primary threat models to systematically evaluate the security robustness of telecom agents."
    ],
    "benignTasks": [
      {
        "name": "Billing & Service Management",
        "description": "Handles billing inquiries, payment status checks, plan charges, invoice-related operations, and service-level changes tied to customer accounts"
      },
      {
        "name": "Customer Lookup",
        "description": "Retrieves subscriber records and verifies customer information such as account ownership, line status, plan details, and linked services"
      },
      {
        "name": "Account Service",
        "description": "Manages account-level changes such as updating service settings, modifying permissions, handling line-level actions, and maintaining account state"
      },
      {
        "name": "Support Ticket",
        "description": "Creates, updates, escalates, resolves, and audits support tickets and internal case records for customer issues"
      },
      {
        "name": "Outage Management",
        "description": "Tracks service outages, checks incident status, communicates restoration timelines, and coordinates operational responses to service disruptions"
      },
      {
        "name": "Orders & Provisioning",
        "description": "Supports device or service orders, subscription changes, activation workflows, and fulfillment-related coordination"
      },
      {
        "name": "Calendar & Scheduling",
        "description": "Schedules appointments, follow-up calls, service callbacks, and other calendar-based customer interactions"
      },
      {
        "name": "Notifications & Messaging",
        "description": "Automates outbound notifications such as service alerts, billing reminders, appointment confirmations, and customer-facing updates"
      },
      {
        "name": "Technician Visit Coordination",
        "description": "Arranges, reschedules, or cancels field technician visits and communicates visit-related logistics to customers"
      },
      {
        "name": "Comprehensive Multi-step Service Workflows",
        "description": "Executes long-horizon tasks that require coordinating multiple tools and systems across billing, account management, scheduling, and communications"
      },
      {
        "name": "Telecom Forum & Knowledge Assistance",
        "description": "Interacts with forum-style or knowledge-sharing environments to answer service questions, summarize issue patterns, and assist customer support workflows"
      }
    ],
    "domainPolicy": "We consider a set of domain-specific telecom policies and service rules governing customer support, subscriber data handling, billing, fraud prevention, and operational actions. These include carrier-facing privacy and service policies such as the *T-Mobile Privacy Notice*, *T-Mobile Privacy Center*, *T-Mobile Financial Privacy Notice*, *T-Mobile Terms & Conditions*, *T-Mobile Open Internet / Network Management* disclosures, and *T-Mobile Scam and Spam Help* guidance. Together, these policies specify restrictions on subscriber-data access, account recovery, financial actions, ticketing workflows, and misuse of customer-service operations.",
    "generalPolicy": "We additionally consider broader telecom and security governance frameworks that regulate telecom infrastructure, operational controls, and secure handling of customer data. These include *3GPP* standards for system and access security (e.g., TS 23.501, TS 33.501, TS 33.117), *O-RAN* security requirements and protocol protections, *NIST SP 800-53* and *NIST SP 1800-33* for access control, auditing, change control, and fraud prevention, as well as *FCC* rules relevant to telecom operational safety and compliance. These frameworks define requirements around authorization, auditability, least privilege, data protection, and safeguards against harmful or unauthorized operational actions.",
    "indirectThreat": null,
    "directThreat": null
  },
  "medical": {
    "overview": [
      "Healthcare is a safety-critical domain where AI agents are increasingly used to assist with clinical and administrative tasks such as diagnostic question answering, treatment planning, medical documentation, and billing or insurance support. These agents often interact with electronic health records (EHRs), clinical tools, and hospital information systems to analyze patient information, request tests, recommend treatments, and generate billing codes (e.g., ICD and CPT codes).",
      "Medical agents typically operate with access to highly sensitive patient data, including protected health information (PHI), laboratory results, imaging reports, and insurance records. They may also influence high-stakes decisions such as medical diagnoses, treatment recommendations, and healthcare billing. Failures or malicious manipulation of these systems can lead to patient harm, insurance fraud, privacy violations, and regulatory risks.",
      "The medical domain is heavily regulated by frameworks such as HIPAA and HITECH for data privacy and security, as well as FDA guidance for Software as a Medical Device (SaMD) and international medical software standards (e.g., ISO 62304 and ISO 82304). To evaluate the robustness of medical AI agents, we construct benign tasks covering three representative clinical workflows: *Diagnostic Q&A*, *Treatment Planning*, and *Billing and Insurance Support*. Grounded in major healthcare regulations and standards, we further derive security risk categories and design adversarial red-teaming tasks to test whether agents can be manipulated into producing unsafe diagnoses, harmful treatments, fraudulent billing actions, or privacy violations."
    ],
    "benignTasks": [
      {
        "name": "Diagnostic Q&A",
        "description": "The agent analyzes patient information including symptoms, medical history, physical examination findings, and test results to determine the most likely diagnosis. The agent may request additional diagnostic tests (e.g., laboratory tests or imaging) and reason over the collected evidence to produce a clinically plausible diagnosis"
      },
      {
        "name": "Treatment Planning",
        "description": "Given a patient diagnosis and clinical context, the agent proposes an initial treatment plan consistent with common medical guidelines. This may include medication recommendations, non-pharmacological interventions, and follow-up monitoring"
      },
      {
        "name": "Billing and Insurance Support",
        "description": "The agent assists with administrative healthcare workflows by generating appropriate billing information based on patient diagnoses and clinical services performed. This includes identifying relevant ICD diagnosis codes and CPT procedure codes and preparing supporting information for insurance documentation"
      }
    ],
    "domainPolicy": "We consider several regulatory and technical frameworks that govern the safe use of AI systems in healthcare environments. These include the *Health Insurance Portability and Accountability Act (HIPAA)*, which defines requirements for protecting protected health information (PHI), including rules on data access, disclosure, and breach notification; the *Health Information Technology for Economic and Clinical Health (HITECH) Act*, which strengthens HIPAA protections by introducing stricter security safeguards, breach reporting obligations, and accountability requirements for entities handling electronic health records; and the *21st Century Cures Act*, which promotes secure interoperability and patient access to electronic health information while prohibiting information blocking practices that restrict appropriate data sharing. We additionally incorporate the *FTC Health Breach Notification Rule (HBNR)*, which requires vendors of personal health records and related entities to notify individuals, the FTC, and in some cases the media when unauthorized acquisition of identifiable health information occurs, extending breach accountability beyond HIPAA-covered entities.",
    "generalPolicy": "We additionally incorporate regulatory guidance and international standards governing medical software safety and clinical AI systems. These include the *FDA Software as a Medical Device (SaMD) Guidance*, which establishes regulatory expectations for AI systems involved in diagnosis and treatment decisions, including requirements for transparency, validation, and lifecycle monitoring; the *U.S. Federal Food, Drug, and Cosmetic Act (FD&C Act)*, which regulates the safety and truthful representation of medical devices and clinical claims; and international medical software standards such as *ISO 62304* and *ISO 82304*, which define best practices for medical software lifecycle management, risk control, and system safety. We also reference principles from the *WHO Guidance on Ethics and Governance of Artificial Intelligence for Health*, which highlights requirements for transparency, accountability, and responsible deployment of healthcare AI systems.",
    "indirectThreat": null,
    "directThreat": null
  }
}
